diseases:
  projector: embed
  path: diseases
  predict: true

death:
  projector: embed
  path: death
  predict: true

cv_drugs:
  projector: embed
  path: cv_drugs
  predict: true

ns_drugs:
  projector: embed
  path: ns_drugs
  predict: true

lifestyle:
  projector: embed
  path: lifestyle
  at_birth: true

hla_alleles:
  projector: embed
  path: hla_alleles
  at_birth: true
  # dropout_mode: block   # drop the entire HLA block with probability dropout_rate
  # dropout_rate: 0.1

sex:
  projector: embed
  path: sex
  at_birth: true

rare_variants:
  projector: embed
  path: rare_variants
  at_birth: true

genetic_pcs:
  type: continuous
  projector: linear
  path: genetic_pcs
  at_birth: true
  input_size: 40
  n_latent_tokens: 5

